# Generated by Django 3.1.7 on 2021-03-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_recipe_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Recipe_Image',
            field=models.ImageField(default='dummy.png', upload_to='recipes/'),
        ),
    ]
